config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'sessions/index'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resource :survey

  root to: "surveys#new"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_many :proposals
	has_many :items, through: :proposals
	has_many :surveys

	def correct_answers	
		Item.joins(:proposal).where('items.candidate_id = ? AND items.candidate_id = proposals.candidate_id', id).size
	end

	def correct_answers_pct_total
		self.correct_answers / Item.joins(:proposal).where('items.candidate_id = proposals.candidate_id').size.to_f
	end

	def correct_answers_by_electors_pct_total
		surveys.present? ? Item.joins(:survey, :proposal).where('surveys.candidate_id = ? AND surveys.candidate_id = proposals.candidate_id', id).size / Item.joins(:proposal).where('items.candidate_id = proposals.candidate_id').size.to_f : 0
	end

	def self.correct_answers_by_unsure_electors_pct_total
		Candidate.items_by_surveys(nil).select {|item| item.correct? }.size / (Survey.where(candidate_id: nil).done.size * 11.0) 
	end

	def self.skipped_answers		
		Item.done.select { |item| item.skipped? }.size
	end

	def self.skipped_answers_pct
		skipped_answers / (Survey.done.size * 11.0)
	end

	def self.correct_answers_by_electors candidate_id, other_candidate_id
		#require 'pry'; binding.pry 		
		#items_by_electors(candidate_id, other_candidate_id).select { |item| item.correct? }.size
	end

	def self.correct_answers_pct_by_electors candidate_id, other_candidate_id
		Item.joins(:survey, :proposal).where('surveys.candidate_id = ? AND proposals.candidate_id = ? AND items.candidate_id = proposals.candidate_id', other_candidate_id, candidate_id).size	/ Item.joins(:survey, :proposal).where('surveys.candidate_id = ? AND surveys.candidate_id = proposals.candidate_id', candidate_id).size.to_f
	end

	def self.items_by_electors candidate_id, other_candidate_id
		Item.joins(:survey).where(:surveys=> {:candidate_id => candidate_id}).joins(:proposal).where(:proposals => {:candidate_id => other_candidate_id}).done
	end

	def self.skipped_answers_pct_by_electors candidate_id
		skipped_answers_by_electors(candidate_id) / items_by_surveys(candidate_id).size.to_f
	end

	def self.skipped_answers_by_electors candidate_id		
		items_by_surveys(candidate_id).select { |item| item.skipped? }.size
	end

	def self.skipped_answers_by_unsure
		items_by_surveys(nil).select { |item| item.skipped? }.size
	end
	
	def self.skipped_answers_pct_by_unsure
		skipped_answers_by_unsure / items_by_surveys(nil).size.to_f
	end

	def self.items_by_surveys candidate_id
		Item.joins(:survey).where(:surveys=> {:candidate_id => candidate_id}).done
	end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :survey
	belongs_to :proposal
	belongs_to :candidate
	
	def self.done		
		joins(:survey).where(:surveys=> {:done => true})
	end

	def self.build
		candidates = Candidate.all.shuffle
		candidates.map do |candidate|
			Item.new(proposal: candidate.proposals.sample)
		end
	end

	def correct?
		self.candidate.try(:id) == proposal.candidate.id
	end

	def skipped?
		candidate.nil?
	end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	belongs_to :candidate
	has_many :items
end

app/models/result.rb
class Result < ActiveRecord::Base
	serialize :correct_answers, Hash
	serialize :correct_answers_by_electors, Hash
	serialize :correct_answers_by_electors_total, Hash
	serialize :done_surveys, Hash

	def self.update survey
		new_result = Result.last.dup
		survey.items.each do |item|
			author_id = item.proposal.candidate_id
			if author_id == item.candidate_id
				new_result.correct_answers[author_id] += 1				 
				new_result.correct_answers_by_electors_total[survey.candidate_id] += 1
				new_result.correct_answers_by_electors[survey.candidate_id][author_id] += 1
			end
		end		
		new_result.done_surveys[survey.candidate_id] += 1
		new_result.save
	end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_one :user
	has_many :items, :dependent => :destroy
	belongs_to :candidate

	attr_accessor :temp_answers

	def self.done
		where(done: true)
	end

	def self.destroy_and_create user
		user.survey.destroy if user.survey.present?
		create(items: Item.build, user: user)
	end

	def self.candidate_pct candidate_id
		where(candidate_id: candidate_id).done.size / done.size.to_f
	end

	def self.unsure_pct
		where(candidate_id: nil).done.size / done.size.to_f
	end

	def correct_answers
		self.items.map { |item| item.proposal.candidate.id }
	end

	def answers
		self.items.map { |item| item.try(:candidate).try(:id) }
	end

	def results
		results_array = []
		correct_answers.each_with_index do |correct_answer, index|
			correct_answer == answers[index] ? results_array.push(true) : results_array.push(false)			
		end
		results_array
	end

	def accuracy
		results.count(true) / results.size.to_f
	end

	def build temp_answers
		update(candidate_id: temp_answers[0], done: true)
		items.each_with_index do |item, index|
			item.candidate_id = temp_answers[index + 1]
			item.save
		end
		#Result.update(self)
		self	
	end

	def done?
		done
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
  
	belongs_to :survey

	 def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	helper_method :current_user
	
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def index
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	before_filter :log_in_user, except: :show
	before_filter :create_survey, only: :new

  def index
    
  end
  
  def new
  	@survey = current_user.survey
  	@items = current_user.survey.items
  end

  def update  	
  	@survey = Survey.find(survey_params[:id])
  	@survey.build(survey_params[:temp_answers].split(','))
  	redirect_to @survey
  end

  def show
  	@survey = Survey.find(params[:format])
  end

  private
  def survey_params  	
    params.require(:survey).permit(:temp_answers, :id)
  end

  def log_in_user
  	#reset_session
  	render 'sessions/index' unless current_user.present?
  end

  def create_survey  	
    current_user.survey.present? && current_user.survey.done? ? redirect_to(current_user.survey) : Survey.destroy_and_create(current_user) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VotoQuiz</title>
  <meta property="og:image" content="<%= image_url('logo.png') %>" />
  <meta property="og:locale" content="pt_BR" />
  <meta property="og:description" content='VotoQuiz é um desafio criado para os eleitores brasileiros. Você é capaz de identificar um candidato através de suas propostas? Faça o teste!' />
  <%= yield :meta %>
  
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= image_tag 'logo.png', class:"navbar-brand" %>     
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a class='brand-link' href="#"><strong class='brand'>VotoQuiz</strong></a> </li>
      </ul> 
      <ul class="nav navbar-nav pull-right">
        <li><a href="#" data-toggle="modal" data-target="#ajuda">Ajuda</a></li>
        <li><a href="#" data-toggle="modal" data-target="#sobre">Sobre</a></li>
        <% if current_user.present? %>
          <li><%= link_to "Sair", signout_path, id: "sign_out" %></li>
        <% else %>
          <%= yield :new_survey_link %>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class='main'>
<%= yield %>

<!-- Modal -->
  <div class="modal fade" id="sobre" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h3 class="modal-title" id="myModalLabel"<strong><strong>>Sobre</strong></h3>
        </div>
        <div class="modal-body">
          <h3 class="text-justify"><p><strong>VotoQuiz</strong> é uma iniciativa independente, cujo objetivo é construir um panorama geral da relação eleitor-candidato, considerando a identificação correta de propostas concretas contidas nos programas de governo. <p>
        </div>        
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="ajuda" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h3 class="modal-title" id="myModalLabel"><strong>Ajuda</strong></h3>
        </div>
        <div class="modal-body">
          <h3 class="text-justify"><p>Você deverá primeiramente escolher o candidato em que deseja votar. Em seguida, serão apresentadas propostas de cada um dos candidatos.</p></h3>
          <h3 class="text-justify"><p> Você deverá identificar o autor da proposta, selecioná-lo e clicar em confirmar para passar para a próxima proposta.</p></h3>
          <h3 class="text-justify"><p>Em qualquer momento é possível corrigir as respostas anteriores. Ao final será exibido um relatório apresentando a porcentagem de acertos geral, e por eleitores de cada candidato.</p></h3>
        </div>        
      </div>
    </div>
  </div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55154851-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/surveys/new.html.erb
<div class='container text-center title'>
	<h1><strong class='instruction'>Selecione o candidato em que irá votar</strong></h1>
</div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-wrap="false" data-interval="false">
	<div class="carousel-inner">
		<div class="item active">
			<div class='container'>
				<div class="row">
					<% Candidate.all.each do |candidate| %>
						<div class="col-xs-2 col-sm-4 col-md-4 col-lg-2">
							<%= link_to image_tag("#{candidate.party.downcase}.jpg", class: "img-rounded", alt: candidate.name), '', class: 'thumbnail', data: { candidate: candidate.id } %>
							<div class="caption">
					      <h4 class='text-center'><%= candidate.name %></h4>
					     	<p class='text-center'><%= candidate.party %></p>
					    </div>
					  </div>					  
					<% end %>
					<div class="col-xs-2 col-sm-4 col-md-4 col-lg-2">
				   	<%= link_to image_tag("unknown_person.jpg", class: "img-rounded", alt: 'Nulo/Branco/Indeciso'), '', class: 'thumbnail', data: { candidate: '' } %>
				   	<div class="caption">
				      <h4 class='text-center'>Branco / Nulo / Indeciso</h4>
				    </div>
			    </div>
				</div>
			</div>
		</div>
		<% @items.all.each do |item| %>
			<div class="item">
				<div class='container'>
				 	<h2 class='text-center proposal'>
				 		<p><strong><%= item.proposal.topic %></strong></p>
				 		<p><i>&ldquo;<%= item.proposal.text %>&rdquo;</i><p>
				 	</h2>
				</div>
				
		 		<div class='container'>
			 		<div class="row">
						<% Candidate.all.each_with_index do |candidate, index| %>
							<div class="col-xs-2 col-sm-2 col-md-1 col-lg-1 thumbnail-div">
								<%= link_to image_tag("#{candidate.party.downcase}.jpg", class: "img-rounded", alt: candidate.name), '', class: 'thumbnail', data: {candidate: candidate.id } %>
								<div class="caption">
						      <h4 class='text-center'><%= candidate.name %></h4>
						     	<p class='text-center'><%= candidate.party %></p>
						    </div>
					    </div>
					    <% if index == 5 %>
					    	<div class="clearfix visible-sm-block"></div>
					    <% end %>					    
						<% end %>
						<div class="col-xs-2 col-sm-2 col-md-1 col-lg-1">
					   	<%= link_to image_tag("unknown_person.jpg", class: "img-rounded", alt: 'Nulo/Branco/Indeciso'), '', class: 'thumbnail', data: { candidate: '' } %>
					   	<div class="caption">
					      <h4 class='text-center'>Não sei</h4>
					    </div>
				    </div>
					</div>					
				</div>
			</div>
		<% end %>
	</div>
</div>
<div class='container'>
	<div class='pull-right buttons'>
		<button type="button" class="btn btn-danger btn-lg" disabled='disabled'>Corrige</button>
		<button type="button" class="btn btn-success btn-lg" disabled='disabled'>Confirma</button>
	</div>
</div>
<%= form_for @survey, url: survey_path(@survey) do |f| %>
	<%= f.hidden_field :temp_answers , class: 'answers'%>
	<%= f.hidden_field :id %>
	<%= f.submit '', class: "submit" %>
<% end %>

<script>
	var answer
	var answers = []
	$('a.thumbnail').on('click', function(e){
		e.preventDefault();
		$(e.currentTarget).parents('.row').children().children('a.thumbnail').removeClass('selected')
		$(e.currentTarget).addClass('selected')
		answer = $(e.currentTarget).data('candidate')
		$('.btn-success').removeAttr('disabled')
	})

	$('.btn-success').on('click', function(){		
		$('.carousel').carousel('next');		
		answers.push(answer)
		$('.btn-danger').removeAttr('disabled')
		$('.btn-success').attr('disabled', true)
		if(answers.length > 11){
			$('.answers').val(answers + '')
			$('.submit').trigger('click')
		} else {
			$('strong.instruction').text('Selecione o candidato ao qual a proposta corresponde (' + answers.length.toString() + '/11)')
		}
	})
	$('.btn-danger').on('click', function(){
		$('.carousel').carousel('prev');
		answers.pop()
		$('strong.instruction').text('Selecione o candidato ao qual a proposta corresponde (' + answers.length.toString() + '/11)')
		if ($.isEmptyObject(answers)){
			$('strong.instruction').text('Selecione o candidato em que irá votar')
			$('.btn-danger').attr('disabled', true)
		}
	})
</script>

app/views/surveys/show.html.erb
<% content_for :meta do %>
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:title" content='Eu acertei <%= (@survey.accuracy * 100).round 2 %>% no VotoQuiz!' />
<% end %>

<% content_for :new_survey_link do %>
  <li><%= link_to 'Faça o teste', root_path, class: 'btn btn-success' %></li> 
<% end %>

<div class='container'>
	<h4>Eleitor <strong><%= @survey.user.name%></strong>, esses são os resultados do <strong>VotoQuiz</strong></h4>
	<div class="fb-share-button pull-right" data-href="<%= survey_url(@survey)%>" data-layout="button" data-width='1000'></div>
	<h1><strong>Acertos: <%= "#{@survey.results.count(true)} de #{@survey.answers.size} (#{(@survey.accuracy * 100).round 2}%)" %></strong></h1>
	<h4><strong><em>Clique sobre um candidato para ver o gráfico de acertos detalhado de seus eleitores</em></strong></h4>
</div>

<div class='container'>
	<div class="row">
		<% @survey.correct_answers.each do |correct_answer| %>
			<% candidate = Candidate.find correct_answer %>
			<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 thumbnail-div">				
				<%= link_to image_tag("#{candidate.party.downcase}.jpg", class: "img-rounded", alt: candidate.name), '', class: 'thumbnail', data: { candidate: candidate.number } %>				 
				<div class="caption">
		      <h4 class='text-center'><%= candidate.name %></h4>
		     	<p class='text-center'><%= candidate.party %></p>		     	
		    </div>		    
   		</div>
		<% end %>
   <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 thumbnail-div">        
      <%= link_to image_tag("unknown_person.jpg", class: "img-rounded", alt: 'Nulo/Branco/Indeciso'), '', class: 'thumbnail', data: { candidate: 'nil' } %>        
      <div class="caption">
        <h4 class='text-center'>Branco / Nulo / Indeciso</h4>             
      </div>        
    </div> 
	</div>
	<div class="row">
		<% @survey.correct_answers.each_with_index do |correct_answer, index| %>
			<% @survey.results[index] ? result = 'fa-check' : result = 'fa-times' %>
			<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 thumbnail-div">
				<p class='text-center'><span class="fa <%= result %> fa-4x"></span></p> 
			</div>
		<% end %>
	</div>
</div>

<div class='container general'></div>
<div class='container intention'></div>
<div class='container electors'></div>
<div class='container graph graph-nil'></div>
<% Candidate.all.each do |candidate| %>
	<div class='container graph graph-<%= candidate.number %>'></div>
	
	<script type="text/javascript">
		$(function () {
			$('.graph-<%= candidate.number %>').highcharts({
				chart: {
            type: 'column'
        },
        title: {
            text: '<%= candidate.name %>'
        },
        subtitle: {
            text: 'Porcentagem de acertos detalhado por eleitorado'
        },
        xAxis: {
        		labels: {
                enabled: false
            }
        },
        yAxis: {
            min: 0,
            max: 100,
            title: {
                text: 'Acertos %'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px"></span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [
        	<% Candidate.all.each_with_index do |other_candidate, index|%>
        		<% data = Array.new(11).fill(nil) %>
        		<% data[index] = (Candidate.correct_answers_pct_by_electors(candidate.id, other_candidate.id) * 100).round 2 %>
            {pointWidth: 60,
            name: '<%= other_candidate.name %>',
            data: <%= data.to_json %>},
          <% end %> 
          {pointWidth: 60,
            <% data = Array.new(12).fill(nil) %>
            <% data[11] = (Candidate.skipped_answers_pct_by_electors(candidate.id) * 100).round 2 %>
            name: 'Não sei',
            data: <%= data.to_json %>}           
        ]
      })
    });
	</script>

<% end %>

<br>
<div class='container text-center'>
  <div class='btn-group'>
  	<button type="button" class="btn btn-primary btn-lg general" data-toggle="tooltip" data-placement="top" title="Mostrar porcentagem de acertos das propostas, independente da intenção de voto">Mostrar gráfico de acertos geral</button>
    <button type="button" class="btn btn-primary btn-lg electors" data-toggle="tooltip" data-placement="top" title="Mostrar porcentagem de acertos total por eleitorado de cada candidato">Mostrar gráfico de acertos por eleitorado</button>
    <button type="button" class="btn btn-primary btn-lg intention" data-toggle="tooltip" data-placement="top" title="Mostrar porcentagem de intenções de voto até o momento">Mostrar intenções de voto</button>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('.graph-nil').highcharts({
      chart: {
          type: 'column'
      },
      title: {
          text: 'Branco / Nulo / Indeciso'
      },
      subtitle: {
          text: 'Porcentagem de acertos detalhada por eleitores'
      },
      xAxis: {
          labels: {
              enabled: false
          }
      },
      yAxis: {
          min: 0,
          max: 100,
          title: {
              text: 'Acertos %'
          }
      },
      tooltip: {
          headerFormat: '<span style="font-size:10px"></span><table>',
          pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
              '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true
      },
      plotOptions: {
          column: {
              pointPadding: 0.2,
              borderWidth: 0
          }
      },
      series: [
        <% Candidate.all.each_with_index do |other_candidate, index|%>
          <% data = Array.new(11).fill(nil) %>
          <% data[index] = (Candidate.correct_answers_pct_by_electors(nil,other_candidate.id) * 100).round 2  %>
          {pointWidth: 60,
          name: '<%= other_candidate.name %>',
          data: <%= data.to_json %>},
        <% end %> 
        {pointWidth: 60,
          <% data = Array.new(12).fill(nil) %>
          <% data[11] = (Candidate.skipped_answers_pct_by_unsure * 100).round 2 %>
          name: 'Não sei',
          data: <%= data.to_json %>}           
      ]
    })
  });
</script>

<script type="text/javascript">
	$( "a.thumbnail" ).on( "click", function(e) {
		e.preventDefault();
		$('div.general').hide();
    $('div.intention').hide();
    $('div.electors').hide();
		$('.graph').hide();
		candidate_number = $(e.currentTarget).data('candidate');
		$('.graph-' + candidate_number.toString()).show();		
	});


	$( "button.general" ).on( "click", function() {
		$('.graph').hide();
    $('div.intention').hide();
    $('div.electors').hide();
		$('div.general').show();
	});

  $( "button.intention" ).on( "click", function() {
    $('.graph').hide();
    $('div.general').hide();
    $('div.electors').hide();
    $('div.intention').show();
  });

  $( "button.electors" ).on( "click", function() {
    $('.graph').hide();
    $('div.general').hide();
    $('div.intention').hide();
    $('div.electors').show();
  });

  $('button.btn').tooltip();

	$(function () {
		$('.general').highcharts({
			chart: {
          type: 'column'
      },
      title: {
          text: 'Resultado geral'
      },
      subtitle: {
          text: 'Porcentagem de acertos geral'
      },
      xAxis: {
      		labels: {
              enabled: false
          }
      },
      yAxis: {
          min: 0,
          max: 100,
          title: {
              text: 'Acertos %'
          }
      },
      tooltip: {
          headerFormat: '<span style="font-size:10px"></span><table>',
          pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
              '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true
      },
      plotOptions: {
          column: {
              pointPadding: 0.2,
              borderWidth: 0
          }
      },
      series: [
      	<% Candidate.all.each_with_index do |candidate, index|%>
      		<% data = Array.new(11).fill(nil) %>
      		<% data[index] = (candidate.correct_answers_pct_total * 100).round 2 %>
          {pointWidth: 60,
          name: '<%= candidate.name %>',
          data: <%= data.to_json %>},
        <% end %>
        {pointWidth: 60,
            <% data = Array.new(12).fill(nil) %>
            <% data[11] = (Candidate.skipped_answers_pct * 100).round 2 %>
            name: 'Não sei',
            data: <%= data.to_json %>} 
      ]
    })
  });

  $(function () {
    $('.electors').highcharts({
      chart: {
          type: 'pie'
      },
      title: {
          text: 'Resultado por eleitorado'
      },
      subtitle: {
          text: 'Porcentagem de acertos por eleitorado'
      },
      tooltip: {
           pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
      },
      plotOptions: {
          pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
              enabled: true,
              format: '<b>{point.name}</b>: {point.percentage:.1f} %',
              style: {
                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
              }
            }
          }
      },

       series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [
          <% Candidate.all.each do |candidate|%>
          {
            name: '<%= candidate.name %>',
            y: <%= (candidate.correct_answers_by_electors_pct_total * 100).round 2 %>
          },
          <% end %>
        {
            
        }]
      }]
      
    })
  });

  $(function () {
    $('.intention').highcharts({
      chart: {
          type: 'column'
      },
      title: {
          text: 'Intenção de votos'
      },
      subtitle: {
          text: 'Porcentagem de eleitores por candidato'
      },
      xAxis: {
          labels: {
              enabled: false
          }
      },
      yAxis: {
          min: 0,
          max: 100,
          title: {
              text: 'Acertos %'
          }
      },
      tooltip: {
          headerFormat: '<span style="font-size:10px"></span><table>',
          pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
              '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true
      },
      plotOptions: {
          column: {
              pointPadding: 0.2,
              borderWidth: 0
          }
      },
      series: [
        <% Candidate.all.each_with_index do |candidate, index|%>
          <% data = Array.new(11).fill(nil) %>
          <% data[index] = (Survey.candidate_pct(candidate.id) * 100).round 2 %>
          {pointWidth: 60,
          name: '<%= candidate.name %>',
          data: <%= data.to_json %>},
        <% end %>
        {pointWidth: 60,
            <% data = Array.new(12).fill(nil) %>
            <% data[11] = (Survey.unsure_pct * 100).round 2 %>
            name: 'Branco/Nulo/Não sei',
            data: <%= data.to_json %>} 
      ]
    })
  });
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&appId=682301135194279&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- resultado geral dos participantes -->